config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resource :sessions, only: %i[new create destroy]
  resources :messages, only: %i[create]

  root "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  has_many :messages, inverse_of: :chat, dependent: :destroy
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :chat, inverse_of: :messages
  belongs_to :user, inverse_of: :messages

  validates :content, presence: true

  scope :after, ->(time: Time.current) { where("created_at >= :time", time: time) }
  scope :before, ->(time: Time.current) { where("created_at <= :time", time: time) }
  scope :in_period, ->(from: 1.week.ago, to: Time.current) { before(time: to).after(time: from) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :messages, inverse_of: :user, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  private

  def current_user
    @_current_user ||= User.find(session.fetch(:user_id)) if session.key?(:user_id)
  end

  def current_chat
    @current_chat ||= CurrentChat.new.load
  end

  def logged_in?
    current_user.present?
  end

  def authorize_user!
    redirect_to new_sessions_path unless logged_in?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authorize_user!

  def index
    @chat = current_chat
    @messages = @chat.messages.preload(:user).order(created_at: :asc)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :authorize_user!

  def create
    message = current_chat.messages.new(user: current_user, content: permitted_params[:content])

    broadcast_notifications(message) if message.save
  end

  private

  def permitted_params
    params.require(:message).permit(:content)
  end

  def broadcast_notifications(message)
    ::NewMessageJob.perform_later(message.id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  layout "auth"
  before_action :authorize_user!, only: %(destroy)

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: permitted_params[:email])

    if user&.authenticate(permitted_params[:password])
      session[:user_id] = user.id

      redirect_to root_path
    else
      @error = "Unable to log in, check your credentials please"
      @user = user || User.new

      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to new_sessions_path
  end

  private

  def permitted_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  layout "auth"

  def new
    @user = User.new
  end

  def create
    user = User.new(permitted_params)

    if user.save
      session[:user_id] = user.id

      redirect_to root_path
    else
      @user = user || User.new

      render :new, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.slim
header
  = current_user.email
  | &nbsp;|&nbsp;
  = link_to "Log Out", sessions_path, method: :delete

br

.chat-container
  - @messages.each do |message|
    .chat-message
      .chat-message__header
        = message.created_at.to_s(:short)
        | &nbsp;|&nbsp;
        = message.user.email
      .chat-message__body
        = message.content

.chat-new-message-form
  = form_for Message.new, url: messages_path, method: :post, remote: true do |form|
    = form.text_field :content, placeholder: "Enter your message", class: "content-input"
    = form.submit "Send", class: "submit-button"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Web Chat
    = stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"

    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0"
  body
    = yield

app/views/layouts/auth.html.slim
doctype html
html
  head
    title Web Chat
    = stylesheet_pack_tag "auth", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "auth", "data-turbolinks-track": "reload"

    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0"
  body
    .container
      = yield

app/views/messages/create.js.slim
| document.querySelector(".chat-new-message-form form").reset();

app/views/users/new.html.slim
- if @user.errors.any?
  ul
    - @user.errors.full_messages.each do |error|
      li.error = error
  br

= form_for @user, url: users_path, method: :post do |form|
  = form.email_field :email, placeholder: "Email"
  br
  = form.password_field :password, placeholder: "Password"
  br
  = form.password_field :password_confirmation, placeholder: "Password"
  br
  br
  = form.submit "Sign Up", class: "submit-button"

br

= link_to "Log in", new_sessions_path